// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wiatwgizafrqmbggxbdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpYXR3Z2l6YWZycW1iZ2d4YmRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjczNzE0MjYsImV4cCI6MjA4Mjk0NzQyNn0.jQNxydJS_I2_E_jKC9d-LtcGgD5k3BR0RxUWl9FmE7k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});